name: Generate ReDoc on Merge to Master

on:
  push:
    branches:
      - master

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Generate ReDoc documentation
        run: uv run scripts/generate_redoc.py
